name: Test

on: [ push, pull_request ]

jobs:
    Consistency:
        name: 'Consistency'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Composer Cache Vars
                id: composer-cache-vars
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"
                    echo "::set-output name=timestamp::$(date +"%s")"

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache-vars.outputs.dir }}
                    key: ${{ runner.os }}-composer-^11.5.3-stable-7.4-${{ steps.composer-cache-vars.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-composer-^11.5.3-stable-7.4-
                        ${{ runner.os }}-composer-^11.5.3-stable-
                        ${{ runner.os }}-composer-^11.5.3-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2
                    coverage: none

            -   name: "Extract tag, branch, version from GITHUB_REF"
                id: "github-ref"
                run: |
                    echo "::set-output name=tag::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/(.*)$#\1#p')"
                    echo "::set-output name=branch::$(echo $GITHUB_REF | sed -E -n 's#^refs/heads/(.*)$#\1#p')"
                    echo "::set-output name=version::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/v?([0-9]+\.)([0-9]+\.)([0-9]+)#\1\2\3#p')"

            -   name: Compare tag version with committed version
                if: steps.github-ref.outputs.version != ''
                run: |
                    composer set-version $(echo ${{ steps.github-ref.outputs.tag }} | sed s/^v//g)
                    test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";

            -   name: Compare extension composer.json with main composer.json
                run: |
                    composer extension-verify-composer-json

            -   name: Build extension artifact
                run: |
                    composer extension-release

    Tests:
        name: 'T3 ${{ matrix.typo3 }} - ${{ matrix.os }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ 'ubuntu-18.04' ]
                typo3: [ '^11.5.3' ]
                php: [ '7.4', '8.0', '8.1' ]
                dependency-version: [ lowest, stable ]
                experimental: [ false ]
                include:
#                    -   os: 'ubuntu-18.04'
#                        php: 8.1
#                        typo3: dev-main
#                        dependency-version: stable
#                        experimental: true
                    -   os: 'windows-latest'
                        php: 7.4
                        typo3: '^11.5.3'
                        dependency-version: stable
                        experimental: false

        continue-on-error: ${{ matrix.experimental }}

        steps:
            -   name: Start database server
                if: matrix.os == 'ubuntu-18.04'
                run: sudo /etc/init.d/mysql start

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Composer Cache Vars
                id: composer-cache-vars
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"
                    echo "::set-output name=timestamp::$(date +"%s")"

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache-vars.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-${{ steps.composer-cache-vars.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, intl, pdo_sqlite, pdo_mysql
                    tools: composer:v2
                    coverage: none

            -   name: Environment Check
                run: |
                    php --version
                    composer --version

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install
                env:
                    COMPOSER_ROOT_VERSION: 7.1.6
                run: |
                    composer update --with "typo3/cms-core:${{ matrix.typo3 }}" --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Lint
                run: php .Build/bin/parallel-lint --exclude .Build .

            # This fails when command reference is not up to date
            -   name: Test Command Reference
                if: matrix.os == 'ubuntu-18.04' && !matrix.experimental
                run: |
                    ./typo3cms commandreference:render
                    git diff --exit-code

            -   name: Test Install (Unix)
                if: matrix.os == 'ubuntu-18.04' && !matrix.experimental
                run: 'php ./typo3cms install:setup --install-steps-config=Tests/Console/Functional/Fixtures/Install/mysql-install.yaml --no-interaction -vvv'

            -   name: Test Install (Windows)
                if: matrix.os == 'windows-latest' && !matrix.experimental
                run: 'php ./typo3cms install:setup --install-steps-config=Tests/Console/Functional/Fixtures/Install/sqlite-install.yaml --no-interaction -vvv'

            -   name: Test
                if: matrix.os == 'ubuntu-18.04' && !matrix.experimental
                run: .Build/bin/phpunit

            -   name: Test - allow failure
                if: matrix.experimental
                run: .Build/bin/phpunit || true

            -   name: Test - Windows
                if: matrix.os == 'windows-latest'
                env:
                    TYPO3_INSTALL_DB_DRIVER: pdo_sqlite
                run: .Build/bin/phpunit
